import { _electron as electron } from 'playwright-core';
import electronPath from 'electron';
import ExcelJS from 'exceljs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const artifacts=path.resolve('test-artifacts');await mkdir(artifacts,{recursive:true});
const file=path.join(artifacts,'teacher-import-example.xlsx');
const book=new ExcelJS.Workbook();book.addWorksheet('안내').addRow(['교사 시트를 선택하세요']);book.addWorksheet('교사').addRows([['교사명','담당과목','역할','메모'],['김민서','국어,문학','일반','예시 교사'],['이서준','수학','필수배치','']]);await book.xlsx.writeFile(file);
const app=await electron.launch({executablePath:electronPath,args:['.'],env:{...process.env,PROCTOR_TEST_HIDDEN:'1',PROCTOR_TEST_DATA:path.join(artifacts,`import-ui-${Date.now()}`)}});
try {
 const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.getByRole('button',{name:'교사 설정',exact:true}).click();
 await page.getByRole('button',{name:'명단 가져오기',exact:true}).click();
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);
 await page.getByRole('button',{name:'엑셀·CSV 파일 선택',exact:true}).click();
 await page.getByLabel('명단 시트',{exact:true}).selectOption('1');
 await page.getByRole('button',{name:'2명 추가',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'2명 추가',exact:true}).isEnabled(),true);
 await page.screenshot({path:path.join(artifacts,'readable-import-preview.png')});
 await page.getByRole('button',{name:'2명 추가',exact:true}).click();
 await page.keyboard.press('Control+s');await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.trim()==='저장됨');
 let doc=await page.evaluate(async()=> (await window.desktop.current()).document);
 assert.deepEqual(doc.teachers[0].subjects,['국어','문학']);assert.equal(doc.teachers[1].role,'designated');
 await page.screenshot({path:path.join(artifacts,'readable-teachers.png')});
 await page.getByRole('button',{name:'명단 가져오기',exact:true}).click();
 await page.getByLabel('Google Sheets 링크',{exact:true}).fill('https://example.com/sheet');
 await page.getByRole('button',{name:'불러오기',exact:true}).click();
 await page.getByText('docs.google.com/spreadsheets/d/',{exact:false}).waitFor();
 await page.getByRole('button',{name:'엑셀·CSV 파일 선택',exact:true}).click();
 await page.getByLabel('명단 시트',{exact:true}).selectOption('1');
 await page.getByText('기존 명단에 같은 이름이 있습니다.',{exact:false}).first().waitFor();
 await page.getByLabel('A열 가져올 항목',{exact:true}).selectOption('');
 assert(await page.getByRole('button',{name:'0명 추가',exact:true}).isDisabled());
 await page.getByLabel('B열 가져올 항목',{exact:true}).selectOption('name');
 assert.equal(await page.getByLabel('A열 가져올 항목',{exact:true}).inputValue(),'');
 await page.getByLabel('A열 가져올 항목',{exact:true}).selectOption('name');
 assert.equal(await page.getByLabel('B열 가져올 항목',{exact:true}).inputValue(),'');
 await page.getByLabel('B열 가져올 항목',{exact:true}).selectOption('subjects');
 await page.screenshot({path:path.join(artifacts,'import-mapping.png')});
 await page.getByRole('button',{name:'취소',exact:true}).click();
 assert.equal((await page.evaluate(async()=> (await window.desktop.current()).document)).teachers.length,2);
 await page.getByRole('button',{name:'전체 삭제',exact:true}).click();
 await page.getByRole('button',{name:'확인',exact:true}).click();
 await page.keyboard.press('Control+s');await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.trim()==='저장됨');
 assert.equal((await page.evaluate(async()=> (await window.desktop.current()).document)).teachers.length,0);
 await page.getByRole('button',{name:'시험 설정',exact:true}).click();
 assert.equal(await page.locator('.room-disclosure').getAttribute('open'),'');
 await page.screenshot({path:path.join(artifacts,'readable-settings.png')});
 await page.getByRole('tab',{name:'감독 방식·배정 기준',exact:false}).click();
 await page.screenshot({path:path.join(artifacts,'readable-rules.png')});
 await page.getByRole('button',{name:'교사 설정',exact:true}).click();
 await app.evaluate(({ipcMain})=>{
   ipcMain.removeHandler('timetable:schools');
   ipcMain.handle('timetable:schools',()=>[{name:'테스트고',region:'서울',code:123}]);
   ipcMain.removeHandler('timetable:comcigan');
   ipcMain.handle('timetable:comcigan',()=>({school:'테스트고',teachers:['','김수*','김수*'],homerooms:[[2,1]],subjects:[],divisor:100,viewLimit:'',original:[],weeks:[]}));
 });
 await page.getByRole('button',{name:'명단 가져오기',exact:true}).click();
 await page.screenshot({path:path.join(artifacts,'import-three-sources.png')});
 await page.getByLabel('명단 가져올 학교 이름').fill('테스트');
 await page.getByRole('button',{name:'학교 검색',exact:true}).click();
 await page.getByRole('button',{name:'테스트고 서울'}).click();
 assert.equal(await page.getByLabel('2행 담임학급',{exact:true}).inputValue(),'1-2');
 assert.equal(await page.getByLabel('3행 담임학급',{exact:true}).inputValue(),'1-1');
 await page.getByText('담임학급 2명 불러옴', {exact:false}).waitFor();
 await page.getByLabel('2행 교사명',{exact:true}).fill('김수진');
 assert.equal(await page.getByLabel('3행 교사명',{exact:true}).inputValue(),'김수*');
 await page.getByLabel('2행 담당과목',{exact:true}).fill('국어, 문학');
 await page.getByLabel('3행 담당과목',{exact:true}).fill('수학');
 await page.screenshot({path:path.join(artifacts,'import-edit-subjects.png')});
 await page.getByRole('button',{name:'2명 추가',exact:true}).click();
 await page.keyboard.press('Control+s');
 await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.trim()==='저장됨');
 const roster=(await page.evaluate(async()=> (await window.desktop.current()).document)).teachers;
 assert.deepEqual(roster.map(t=>t.name),['김수진','김수*']);
 assert.notEqual(roster[0].id,roster[1].id);
 assert.deepEqual(roster.map(t=>t.subjects),[['국어','문학'],['수학']]);
 assert.deepEqual(errors,[]);
 await writeFile(path.join(artifacts,'teacher-import-ui-report.json'),JSON.stringify({passed:true,imported:2,cancelPreserves:true,duplicateWarning:true,rendererErrors:errors},null,2));
 console.log('교사 XLSX 파일 선택 → 시트/열 미리보기 → 추가/저장, 열 연결, 잘못된 링크 안내, 동명이인 경고, 취소, 전체 삭제 검증 통과');
} finally {await app.evaluate(({app})=>app.exit(0)).catch(()=>{});}

